export const AnalysisColors = {
  screen: '#F4F8FC',
  background: '#FFFFFF',
  textPrimary: '#2D3748',
  textSecondary: '#5A6472',
  primary: '#6B9FD4',
  primaryLight: '#EDF2FF',
  progressTrack: '#E2EAF5',
  success: '#22C55E',
  successLight: '#DCFCE7',
  cardBorder: '#E8EEF7',
  button: '#5B8DEF',
  buttonText: '#FFFFFF',
  scoreRing: '#6B9FD4',
  highlightGreen: '#16A34A',
  metricBlue: '#6B9FD4',
  metricRed: '#EF4444',
  metricGreen: '#22C55E',
  metricPurple: '#8B5CF6',
  metricOrange: '#F97316',
  // 지표/개선 포인트 카드 틴트
  tintBlueBg: '#EDF3FE',
  tintBlueBorder: '#D9E5FB',
  tintYellowBg: '#FFF9EC',
  tintYellowBorder: '#F3E8C8',
  tintGreenBg: '#F0FAF0',
  tintGreenBorder: '#D7EFD7',
  tintRedBg: '#FEF2F1',
  tintRedBorder: '#F8DAD6',
};

export const MascotVariants = {
  recording: 0,
  result: 1,
  analyzing: 6,
} as const;
